### ISSUE TITLE
hellooooooooo 

### ISSUE THREAD

**Issue by sesang82** [XeNTaXTools/XeNTaXTools-Legacy#1]
https://web.archive.org/web/20231013070601/https://forum.xentax.com/viewtopic.php?f=18&t=17800   TLOUTexEditor_U1.rar ... that tool is here????? I looking for it

**Comment by VertofChest** [comment]
It seems like the link provided doesn't lead to the right place.

**Comment by sesang82** [comment]
I checked again and the link works! I found the current tool. Ty
